language: go
before_install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v -covermode=count -coverprofile=coverage.txt ./geodelta
after_success:
  - bash <(curl -s https://codecov.io/bash)
